name: Go Midnight Build

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  packages: write

jobs:
  midnight-build:
    name: Build Go Midnight Version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.5

    - name: Install dependencies
      run: go mod tidy

    - name: Build the Go application
      run: go build -o airbox-agent-midnight

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: airbox-agent-midnight
        path: ./airbox-agent-midnight
