name: Go Production Build

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.5

    - name: Install dependencies
      run: go mod tidy

    - name: Build the Go application
      run: |
        VERSION=$(echo ${{ github.event.release.tag_name }})
        go build -o airbox-agent-$VERSION

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: airbox-agent-${{ github.event.release.tag_name }}
        path: ./airbox-agent-${{ github.event.release.tag_name }}
