name: Go Develop Build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  develop-build:
    name: Build Go Develop Version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Build the Go application
      run: go build -o airbox-agent-develop

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: airbox-agent-develop
        path: ./airbox-agent-develop
